name: 'nba_pipeline'
version: '1.0.0'
config-version: 2

profile: 'nba_pipeline'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  nba_pipeline:
    staging:
      +materialized: view
    marts:
      +materialized: table
