[project]
name = "ingestion"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Tushar", email = "tusharcs0112@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "db",
    "httpx>=0.28.1",
    "nba_api",
    "prefect>=3.8.4",
    "psycopg[binary]>=3.3.5",
    "pydantic-settings>=2.15.0",
    "sqlalchemy>=2.0.52",
]

[project.scripts]
ingestion = "ingestion:main"

[build-system]
requires = ["uv_build>=0.11.33,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[tool.uv.sources]
db = { path = "../db", editable = true }
